---
# tasks file for apache_install
- name: Install apache
  yum:
    name: httpd
    state: latest

- name: Start httpd service
  service:
    name: httpd
    state: started

- name: Enable service httpd
  service:
    name: httpd
    enabled: yes
  notify:
    - restart apache
